using System;

namespace GameData
{
	public enum AttrType
	{
		MoveSpeed = 101,
		ActSpeed,
		Lv = 1001,
		Fighting = 1007,
		VipLv = 1010,
		Atk = 201,
		Defence = 601,
		HpLmt = 301,
		PveAtk = 1304,
		PvpAtk,
		HitRatio,
		DodgeRatio,
		CritRatio,
		DecritRatio,
		CritHurtAddRatio,
		ParryRatio,
		DeparryRatio,
		ParryHurtDeRatio,
		SuckBloodScale = 513,
		HurtAddRatio = 1315,
		HurtDeRatio,
		PveHurtAddRatio,
		PveHurtDeRatio,
		PvpHurtAddRatio,
		PvpHurtDeRatio,
		AtkMulAmend = 202,
		DefMulAmend = 1323,
		HpLmtMulAmend,
		PveAtkMulAmend,
		PvpAtkMulAmend,
		ActPointRecoverSpeedAmend = 108,
		VpLmt = 1330,
		VpLmtMulAmend,
		VpAtk = 1333,
		VpAtkMulAmend,
		VpResume = 1332,
		IdleVpResume = 1336,
		Vp = 1335,
		WaterBuffAddProbAddAmend = 1221,
		WaterBuffDurTimeAddAmend = 1224,
		ThunderBuffAddProbAddAmend = 1231,
		ThunderBuffDurTimeAddAmend = 1234,
		HealIncreasePercent = 1337,
		CritAddValue = 1339,
		HpRestore,
		Energy = 1004,
		EnergyLmt,
		Exp = 1002,
		ExpLmt,
		Diamond = 1008,
		Gold,
		RechargeDiamond = 1011,
		Honor,
		CompetitiveCurrency,
		SkillPoint = 1015,
		Reputation = 1341,
		BuffMoveSpeedMulPosAmend = 707,
		BuffActSpeedMulPosAmend = 709,
		SkillTreatScaleBOAtk = 514,
		SkillTreatScaleBOHpLmt,
		SkillIgnoreDefenceHurt,
		SkillNmlDmgScale = 501,
		SkillNmlDmgAddAmend,
		SkillHolyDmgScaleBOMaxHp = 511,
		SkillHolyDmgScaleBOCurHp,
		Affinity = 103,
		OnlineTime = 1329,
		ActPointLmt = 107,
		ActPoint = 106,
		Hp = 1006,
		ExpAddRate = 1338,
		RealHpLmt = 10001,
		RealVpLmt,
		RealMoveSpeed,
		RealActionSpeed
	}
}
