using System;

public class BaseServiceMgr
{
	public static void InitGameSettingManagers()
	{
	}

	public static void InitManagers()
	{
		FPSManager.Instance.Init();
		SoundManager.CreateInstance();
		SDKManager.Instance.Init();
		NativeCallManager.Instance.Init();
		VoiceSDKManager.Instance.Init();
		PushNotificationManager.Instance.Init();
		BTLoader.Init();
		AssetManager.AssetOfTPManager.Instance.Init();
		UIQueueManager.Instance.Init();
		UIStackManager.Instance.Init();
		GuideManager.Instance.Init();
		BadWordsFilter.Instance.Init();
		NetworkManager.Instance.Init();
		LoginManager.Instance.Init();
		ReconnectManager.Instance.Init();
		EntityWorld.Instance.Init();
		MySceneManager.Instance.Init();
		AOIService.Instance.Init();
		CityManager.Instance.Init();
		InstanceManager.Init();
		GangFightManager.Instance.Init();
		BountyManager.Instance.Init();
		DungeonManager.Instance.Init();
		DefendFightManager.Instance.Init();
		SurvivalManager.Instance.Init();
		PVPManager.Instance.Init();
		ServerGMManager.Instance.Init();
		ElementInstanceManager.Instance.Init();
		WildBossManager.Instance.Init();
		SpecialFightManager.Instance.Init();
		DarkTrialManager.Instance.Init();
		FashionManager.Instance.Init();
		RadarManager.Instance.Init();
		MemCollabManager.Instance.Init();
		GodWeaponProgressManager.Instance.Init();
		SystemOpenProgressManager.Instance.Init();
		BadgeManager.Instance.Init();
		ActorVisibleManager.Instance.Init();
		NPCManager.Instance.Init();
		WildBossManager.Instance.Init();
		TaskNPCManager.Instance.Init();
		WildBossNPCManager.Instance.Init();
		HearthNPCManager.Instance.Init();
		CollectionNPCManager.Instance.Init();
		PetManager.Instance.Init();
		BackpackManager.Instance.Init();
		EnergyManager.Instance.Init();
		BoxRewardManager.Instance.Init();
		GuildManager.Instance.Init();
		TeamManager.Instance.Init();
		MultiPlayerManager.Instance.Init();
		GoldBuyManager.Instance.Init();
		ElementManager.Instance.Init();
		ChangeCareerManager.Instance.Init();
		GlobalManager.Instance.Init();
		EquipmentManager.Instance.Init();
		SignInManager.Instance.Init();
		MainTaskManager.Instance.Init();
		DailyTaskManager.Instance.Init();
		CharacterManager.Instance.Init();
		UpgradeManager.Instance.Init();
		GuildWarManager.Instance.Init();
		VIPManager.Instance.Init();
		RechargeManager.Instance.Init();
		RankingManager.Instance.Init();
		SkillUIManager.Instance.Init();
		RoleTalentManager.Instance.Init();
		TipsManager.Instance.Init();
		EliteDungeonManager.Instance.Init();
		TeamBasicManager.Instance.Init();
		WildMonsterManager.Instance.Init();
		GodSoldierManager.Instance.Init();
		GodWeaponManager.Instance.Init();
		SkillRuneManager.Instance.Init();
		GuildBossManager.Instance.Init();
		RenameManager.Instance.Init();
		HuntManager.Instance.Init();
		RankUpManager.Instance.Init();
		RankUpChangeManager.Instance.Init();
		MultiPVPManager.Instance.Init();
		TramcarManager.Instance.Init();
		GuildSkillManager.Instance.Init();
		PetTaskManager.Instance.Init();
		GuildStorageManager.Instance.Init();
		MarketManager.Instance.Init();
		LimitTimeMarketManager.Instance.Init();
		GuildMarketManager.Instance.Init();
		XMarketManager.Instance.Init();
		TransactionNPCManager.Instance.Init();
		GlobalBattleNetwork.Instance.Init();
		BattleBlackboard.Instance.Init();
		LocalInstanceHandler.Instance.Init();
		LocalBattleHandler.Instance.Init();
		LocalAgent.Intergrate(LocalInstanceHandler.Instance, LocalBattleHandler.Instance);
		BattleCalculator.Init();
		WarningGraghHandler.Init();
		BattleTimeManager.Instance.Init();
		BattleDialogManager.Instance.Init();
		ChatManager.Instance.Init();
		FriendManager.Instance.Init();
		MailManager.Instance.Init();
		TitleManager.Instance.Init();
		BroadcastManager.Instance.Init();
		BillboardManager.Instance.Init();
		FloatTextAddManager.Instance.Init();
		GemManager.Instance.Init();
		Activity7DayManager.Instance.Init();
		ActivityCenterManager.Instance.Init();
		WingManager.Instance.Init();
		ConsumeRechargeManager.Instance.Init();
		LuckDrawManager.Instance.Init();
		NoticeManager.Instance.Init();
		OperateActivityManager.Instance.Init();
		AchievementManager.Instance.Init();
		StrongerManager.Instance.Init();
		FirstPayManager.Instance.Init();
		InvestFundManager.Instance.Init();
		GrowUpPlanManager.Instance.Init();
		ActivityTossDiscountManager.Instance.Init();
		NewPeoperGiftPackageManager.Instance.Init();
		CheckPlayerInfoManager.Instance.Init();
		OffHookManager.Instance.Init();
		MushroomHitManager.Instance.Init();
		BossBookManager.Instance.Init();
		GiftExchangeManager.Instance.Init();
		DayGiftManager.Instance.Init();
		VipTasteCardManager.Instance.Init();
		AcOpenServerManager.Instance.Init();
		RedBagManager.Instance.Init();
	}

	public static void ReleaseManagers()
	{
		WarningGraghHandler.Release();
		BattleCalculator.Release();
		GlobalBattleNetwork.Instance.Release();
		BattleBlackboard.Instance.Release();
		LocalBattleHandler.Instance.Release();
		LocalInstanceHandler.Instance.Release();
		CityManager.Instance.Release();
		AOIService.Instance.Release();
		EntityWorld.Instance.Release();
		InstanceManager.Release();
		LoginManager.Instance.Release();
		ReconnectManager.Instance.Release();
		NetworkManager.Instance.Release();
		for (int i = 0; i < BaseSubSystemManager.ListManager.get_Count(); i++)
		{
			BaseSubSystemManager.ListManager.get_Item(i).Release();
		}
	}
}
